language: objective-c
osx_image: xcode9.1
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "IntentDemo.xcodeproj" -scheme "IntentDemo" -destination "OS=11.0,name=iPhone X" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty