language: objective-c
osx_image: xcode10.1
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "IntentDemo.xcodeproj" -scheme "Intent" -configuration Debug ONLY_ACTIVE_ARCH=NO build
